name: Hello world

on:
    push:
        branches:
            - main

    workflow_dispatch:

jobs:
    hello-world:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Runs the "Hello world" shell script
              run: ./index.sh
